mqtt.broker.url=ssl://53cc1d1dc297463f9f511baf26ee908e.s1.eu.hivemq.cloud:8883
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}



# Database configuration for production environmentt  
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# ─── CORS (pour React en dev) ─────────────────────────────
app.cors.allowed-origins=${ALLOWED_ORIGINS}